import { EventBus, clamp, distance, fromAngle, normalize, pick, seededRng, shuffle } from './core.js';
import { MECHS, getMech, EVENT_DEFS, ROOM_TEMPLATES, MODULES } from './data.js';
import { PlayerMech, Enemy } from './actors.js';
import { projectileHitsActor, saberHitsActor, generateRoomGraph, rollModuleChoices, loadProfile, recordRun, saveProfile, markDialogue, selectDialogue } from './systems.js';
export class Game{
constructor({renderer,input,ui,audio}){this.renderer=renderer;this.input=input;this.ui=ui;this.audio=audio;this.bus=new EventBus();this.profile=loadProfile();this.selectedMech=this.profile.selectedMech||'vanguard';this.state='base';this.previousState=null;this.time=0;this.bounds={left:-9,right:9,top:-6,bottom:6};this.player=null;this.run=null;this.room=null;this.enemies=[];this.projectiles=[];this.missiles=[];this.slashes=[];this.hazards=[];this.vfx=[];this.damageNumbers=[];this.decoys=[];this.roomClearTimer=0;this.waveDelay=0;this.pendingResult=0;this.vibrate=this.profile.settings.vibration;this.bindEvents();this.showBase();}
bindEvents(){this.bus.on('bossPhase',({phase})=>{this.ui.notify(`守墓者进入 PHASE ${phase}`);this.renderer.camera.shake=12*this.renderer.dpr;});document.addEventListener('visibilitychange',()=>{if(document.hidden&&this.state==='combat')this.pause();});}
showBase(){this.state='base';this.input.setEnabled(false);const lastRun=this.profile.history.at(-1)||null,dialogue=selectDialogue(this.profile,lastRun);this.profile=markDialogue(this.profile,dialogue);saveProfile(this.profile);this.ui.showBase(this.profile,MECHS,dialogue,this.selectedMech,(id)=>{this.selectedMech=id;this.profile.selectedMech=id;saveProfile(this.profile);this.audio.play('select');this.showBase();},()=>this.startRun());}
startRun(){this.audio.unlock();const seed=Date.now()^Math.floor(Math.random()*0xffffff),mech=getMech(this.selectedMech);this.run={seed,graph:generateRoomGraph(seed,10),depth:0,modules:[],mechTags:[...mech.tags],credits:0,permanentEarned:0,kills:0,secondaryKills:0,roomsCleared:0,deathCause:null,reachedBoss:false,lowHpClear:false,events:[],nextElite:false};this.player=new PlayerMech(mech,this.run.modules);this.showRoute();}
showRoute(){this.state='route';this.input.setEnabled(false);this.ui.setCombatVisible(false);const node=this.run.graph.nodes[this.run.depth];this.ui.showRoute(node,(index)=>this.chooseRoom(index));}
chooseRoom(index){const node=this.run.graph.nodes[this.run.depth],choice=node.choices[index]||node.choices[0];this.audio.play('select');if(this.run.nextElite&&choice.type==='combat'){choice.elite=true;choice.template=Math.random()<.5?'elite_blade':'elite_cannon';this.run.nextElite=false;}if(choice.type==='combat')this.startCombat(choice);else if(choice.type==='shop')this.showShop();else if(choice.type==='repair'){this.player.hp=Math.min(this.player.maxHp,this.player.hp+this.player.maxHp*.35);this.ui.notify('耐久恢复 35%');this.advanceDepth();}else if(choice.type==='event')this.showEvent();}
startCombat(choice){this.state='combat';this.input.clear();this.input.setEnabled(true);this.ui.hidePanel();this.ui.setCombatVisible(true);this.clearRoomObjects();const template=ROOM_TEMPLATES.find((t)=>t.id===choice.template)||ROOM_TEMPLATES[0];this.room={...template,reward:choice.reward,elite:Boolean(choice.elite||template.elite),boss:Boolean(choice.boss||template.boss),waveIndex:-1,clear:false};if(this.room.boss)this.run.reachedBoss=true;this.player.resetForRoom({x:0,y:4.4});this.player.refreshBuild(this.run.modules,true);this.waveDelay=.65;this.ui.notify(this.room.boss?'区域首领接近':this.room.name,1.5);}
clearRoomObjects(){this.enemies.length=0;this.projectiles.length=0;this.missiles.length=0;this.slashes.length=0;this.hazards.length=0;this.vfx.length=0;this.damageNumbers.length=0;this.decoys.length=0;this.roomClearTimer=0;this.pendingResult=0;}
spawnNextWave(){this.room.waveIndex+=1;const wave=this.room.waves[this.room.waveIndex];if(!wave)return false;const rng=seededRng(this.run.seed+this.run.depth*100+this.room.waveIndex*31),positions=this.spawnPositions(wave.length,rng);wave.forEach((type,i)=>{const scale=this.run.depth>=7&&!['boss','eliteBlade','eliteCannon'].includes(type)?1.12:1;this.enemies.push(new Enemy(type,positions[i].x,positions[i].y,scale));});this.ui.notify(`WAVE ${this.room.waveIndex+1} / ${this.room.waves.length}`,1.1);return true;}
spawnPositions(count,rng){const positions=[];for(let i=0;i<count;i+=1){const angle=i/count*Math.PI*2+rng()*.5,r=3.5+rng()*2.1;positions.push({x:Math.cos(angle)*r,y:Math.sin(angle)*r-1.2});}return positions;}
update(dt){this.time+=dt;if(this.state==='combat')this.updateCombat(dt);this.updateEffects(dt);if(this.state==='combat')this.ui.updateHud(this);}
render(){this.renderer.render(this);}
updateCombat(dt){const input=this.input.update((x,y)=>this.renderer.screenToWorld(x,y),this.player);if(input.pressed.pause)return this.pause();this.player.update(dt,input,this);for(const enemy of this.enemies)enemy.update(dt,this);this.updateProjectiles(dt);this.updateMissiles(dt);this.updateSlashes(dt);this.updateHazards(dt);this.resolveBodyCollisions();if(this.player.dead){this.pendingResult+=dt;if(this.pendingResult>1.1){this.run.deathCause=this.player.lastHitType||'enemy';this.finishRun(false);}return;}if(this.waveDelay>0){this.waveDelay-=dt;if(this.waveDelay<=0)this.spawnNextWave();}const living=this.enemies.some((e)=>!e.dead);if(!living&&this.waveDelay<=0){if(this.room.waveIndex+1<this.room.waves.length)this.waveDelay=.85;else if(!this.room.clear){this.room.clear=true;this.roomClearTimer=.75;}}if(this.room.clear){this.roomClearTimer-=dt;if(this.roomClearTimer<=0)this.completeCombatRoom();}}
updateProjectiles(dt){for(const shot of this.projectiles){shot.life-=dt;shot.x+=Math.cos(shot.angle)*shot.speed*dt;shot.y+=Math.sin(shot.angle)*shot.speed*dt;if(shot.owner==='player'){for(const enemy of this.enemies){if(shot.hitIds?.has(enemy.id)||!projectileHitsActor(shot,enemy))continue;shot.hitIds||=new Set();shot.hitIds.add(enemy.id);const result=enemy.receiveHit(this,{damage:shot.damage,source:shot.source||shot,stagger:.12,knockback:1.25,force:.65,type:shot.type,owner:'primary'});if(result.applied){this.player.gainOverdrive(result.damage*.32);if(result.killed)this.registerKill(enemy,'primary');}if(shot.ricochet>0){const target=this.getNearestEnemies(enemy,1,5,(e)=>!shot.hitIds.has(e.id))[0];if(target){shot.angle=Math.atan2(target.y-shot.y,target.x-shot.x);shot.ricochet-=1;shot.damage*=.82;continue;}}if(shot.pierce>0){shot.pierce-=1;shot.damage*=.82;}else shot.life=0;break;}}else if(projectileHitsActor(shot,this.player)){this.player.lastHitType=shot.type==='sniper'?'sniper':'projectile';this.player.takeDamage(this,shot.damage,shot.source||shot,shot.type);shot.life=0;}if(shot.x<this.bounds.left-1||shot.x>this.bounds.right+1||shot.y<this.bounds.top-1||shot.y>this.bounds.bottom+1)shot.life=0;}this.projectiles=this.projectiles.filter((s)=>s.life>0);}
updateMissiles(dt){for(const missile of this.missiles){missile.life-=dt;if(missile.target?.dead)missile.target=null;if(!missile.target)missile.target=this.getNearestEnemies(missile,1,12)[0]||null;if(missile.target){const desired=Math.atan2(missile.target.y-missile.y,missile.target.x-missile.x);let delta=desired-missile.angle;while(delta>Math.PI)delta-=Math.PI*2;while(delta<-Math.PI)delta+=Math.PI*2;missile.angle+=clamp(delta,-dt*4.8,dt*4.8);}missile.speed=Math.min(12,missile.speed+dt*5);missile.x+=Math.cos(missile.angle)*missile.speed*dt;missile.y+=Math.sin(missile.angle)*missile.speed*dt;const target=this.enemies.find((e)=>!e.dead&&distance(missile,e)<e.radius+.25);if(target){this.explodeMissile(missile,target);missile.life=0;}}this.missiles=this.missiles.filter((m)=>m.life>0);}
explodeMissile(missile){const victims=this.enemies.filter((e)=>!e.dead&&distance(missile,e)<1.25);for(const enemy of victims){const result=enemy.receiveHit(this,{damage:missile.damage,source:missile,stagger:.25,knockback:2.2,force:1,type:'missile',owner:'ordnance'});if(result.applied){this.player.gainOverdrive(result.damage*.25);if(result.killed)this.registerKill(enemy,'ordnance');}if(missile.pull){const dir=normalize({x:missile.x-enemy.x,y:missile.y-enemy.y});enemy.vx+=dir.x*missile.pull;enemy.vy+=dir.y*missile.pull;}}this.spawnVfx({type:'explosion',x:missile.x,y:missile.y,color:'#ff8b43',life:.58,scale:1.2});if(missile.cluster)for(let i=0;i<missile.cluster;i+=1)this.spawnProjectile({owner:'player',x:missile.x,y:missile.y,angle:i/missile.cluster*Math.PI*2,speed:8,damage:missile.damage*.34,color:'#ffbd65',life:.55,radius:.12,type:'cluster',source:{x:missile.x,y:missile.y}});}
updateSlashes(dt){for(const slash of this.slashes){slash.life-=dt;if(slash.owner==='player'){for(const enemy of this.enemies){if(slash.hitIds.has(enemy.id)||!saberHitsActor(slash.base,slash.tip,slash.width,enemy))continue;if(distance(slash,enemy)>slash.range+enemy.radius)continue;slash.hitIds.add(enemy.id);const result=enemy.receiveHit(this,{damage:slash.damage,source:{x:this.player.x,y:this.player.y},stagger:.28,knockback:3.5,force:1.2,type:'saber',mark:slash.mark,owner:'secondary'});if(result.applied){this.player.gainOverdrive(result.damage*.38);if(result.killed)this.registerKill(enemy,'secondary');}}}else if(!slash.hitPlayer&&distance(slash,this.player)<slash.range+this.player.radius){slash.hitPlayer=true;this.player.lastHitType='melee';this.player.takeDamage(this,slash.damage,slash.source,'melee');}}this.slashes=this.slashes.filter((s)=>s.life>0);}
updateHazards(dt){for(const h of this.hazards){h.delay-=dt;if(h.delay<=0&&!h.triggered){h.triggered=true;if(distance(h,this.player)<h.radius+this.player.radius){this.player.lastHitType='artillery';this.player.takeDamage(this,h.damage,h.owner||h,'artillery');}this.spawnVfx({type:'explosion',x:h.x,y:h.y,color:'#ff4d6a',life:.65,scale:h.radius});this.renderer.camera.shake=Math.max(this.renderer.camera.shake,8*this.renderer.dpr);}if(h.triggered)h.life-=dt;}this.hazards=this.hazards.filter((h)=>!h.triggered||h.life>0);}
updateEffects(dt){for(const v of this.vfx)v.life-=dt;for(const n of this.damageNumbers){n.life-=dt;n.y-=dt*.65;}for(const d of this.decoys)d.life-=dt;this.vfx=this.vfx.filter((v)=>v.life>0);this.damageNumbers=this.damageNumbers.filter((n)=>n.life>0);this.decoys=this.decoys.filter((d)=>d.life>0);}
resolveBodyCollisions(){const actors=[this.player,...this.enemies.filter((e)=>!e.dead)];for(let i=0;i<actors.length;i+=1)for(let j=i+1;j<actors.length;j+=1){const a=actors[i],b=actors[j],dx=b.x-a.x,dy=b.y-a.y,d=Math.hypot(dx,dy)||.001,min=a.radius+b.radius;if(d>=min)continue;const push=(min-d)*.5,nx=dx/d,ny=dy/d;a.x-=nx*push;a.y-=ny*push;b.x+=nx*push;b.y+=ny*push;}}
registerKill(enemy,source){this.run.kills+=1;if(source==='secondary')this.run.secondaryKills+=1;this.run.credits+=enemy.def.score||8;}
completeCombatRoom(){this.room.clear=false;this.run.roomsCleared+=1;if(this.player.hp/this.player.maxHp<.15)this.run.lowHpClear=true;const healPct=this.player.stats.effects.roomHealPct||0;if(healPct)this.player.hp=Math.min(this.player.maxHp,this.player.hp+this.player.maxHp*healPct);if(this.room.boss)return this.finishRun(true);const reward=this.room.reward;if(reward==='credits'){this.run.credits+=40;this.ui.notify('获得战术核心 ●40');return this.advanceDepth();}if(reward==='permanent'){this.run.permanentEarned+=3;this.ui.notify('获得舰队数据 ◆3');return this.advanceDepth();}if(reward==='repair'){this.player.hp=Math.min(this.player.maxHp,this.player.hp+this.player.maxHp*.3);return this.advanceDepth();}const choices=rollModuleChoices(this.run,reward,this.run.seed+this.run.depth*211);this.state='reward';this.input.setEnabled(false);this.ui.setCombatVisible(false);this.ui.showReward(choices,reward,(index)=>{const module=choices[index]||choices[0];this.run.modules.push(module);this.player.refreshBuild(this.run.modules,true);this.audio.play('select');this.advanceDepth();});}
advanceDepth(){this.run.depth+=1;if(this.run.depth>=this.run.graph.nodes.length)return this.finishRun(true);this.showRoute();}
showShop(){this.state='shop';this.input.setEnabled(false);this.ui.setCombatVisible(false);const inventory=shuffle(MODULES.filter((m)=>!this.run.modules.some((x)=>x.id===m.id)),seededRng(this.run.seed+this.run.depth*19)).slice(0,3),render=()=>this.ui.showShop(this.run,inventory,(index)=>{if(this.run.credits<35)return;const[module]=inventory.splice(index,1);if(!module)return;this.run.credits-=35;this.run.modules.push(module);this.player.refreshBuild(this.run.modules,true);this.audio.play('select');render();},()=>{if(this.run.credits<25)return;this.run.credits-=25;this.player.hp=Math.min(this.player.maxHp,this.player.hp+this.player.maxHp*.28);this.audio.play('select');render();},()=>this.advanceDepth());render();}
showEvent(){this.state='event';this.input.setEnabled(false);this.ui.setCombatVisible(false);const event=pick(EVENT_DEFS,seededRng(this.run.seed+this.run.depth*73));this.ui.showEvent(event,(index)=>{const choice=event.choices[index]||event.choices[0];this.run.events.push(`${event.id}:${choice.id}`);if(choice.permanent)this.run.permanentEarned+=choice.permanent;if(choice.credits)this.run.credits+=choice.credits;if(choice.nextElite)this.run.nextElite=true;if(choice.healPct)this.player.hp=Math.min(this.player.maxHp,this.player.hp+this.player.maxHp*choice.healPct);if(choice.hpCostPct)this.player.hp=Math.max(1,this.player.hp-this.player.hp*choice.hpCostPct);if(choice.rareModule){const rare=shuffle(MODULES.filter((m)=>m.rarity==='rare'&&!this.run.modules.some((x)=>x.id===m.id)),seededRng(this.run.seed+99))[0];if(rare){this.run.modules.push(rare);this.player.refreshBuild(this.run.modules,true);}}this.audio.play('select');this.advanceDepth();});}
finishRun(victory){if(this.state==='result')return;this.state='result';this.input.setEnabled(false);this.clearHostileObjects();const report={victory,depth:this.run.depth+1,roomsCleared:this.run.roomsCleared,kills:this.run.kills,secondaryKills:this.run.secondaryKills,permanentEarned:this.run.permanentEarned+(victory?5:0),deathCause:this.run.deathCause,reachedBoss:this.run.reachedBoss,lowHpClear:this.run.lowHpClear,mechId:this.selectedMech,modules:this.run.modules.map((m)=>m.id),events:this.run.events};this.profile=recordRun(this.profile,report);saveProfile(this.profile);this.ui.showResult(report,()=>this.showBase());}
clearHostileObjects(){this.projectiles.length=0;this.missiles.length=0;this.slashes.length=0;this.hazards.length=0;}
pause(){if(this.state!=='combat')return;this.previousState='combat';this.state='paused';this.input.setEnabled(false);this.ui.setCombatVisible(false);this.ui.showPause(()=>this.resume(),()=>this.finishRun(false));}
resume(){if(this.state!=='paused')return;this.state='combat';this.input.clear();this.input.setEnabled(true);this.ui.hidePanel();this.ui.setCombatVisible(true);}
spawnProjectile(data){this.projectiles.push({...data,hitIds:new Set()});}spawnMissile(data){this.missiles.push(data);}spawnSlash(data){this.slashes.push({...data,maxLife:data.life,hitIds:new Set()});}
spawnEnemySlash(enemy,angle,damage,range){const dir=fromAngle(angle),base={x:enemy.x+dir.x*.2,y:enemy.y+dir.y*.2},tip={x:enemy.x+dir.x*range,y:enemy.y+dir.y*range};this.slashes.push({owner:'enemy',x:enemy.x,y:enemy.y,angle,base,tip,range,width:.3,damage,color:enemy.def.color,life:.2,maxLife:.2,hitIds:new Set(),source:{x:enemy.x,y:enemy.y},hitPlayer:false});}
spawnHazard(data){this.hazards.push({...data,maxDelay:data.delay,life:.18,triggered:false});}spawnVfx(data){this.vfx.push({...data,maxLife:data.life});}spawnDamageNumber(x,y,value,kill=false){this.damageNumbers.push({x,y,value,kill,life:.65,maxLife:.65});}spawnDecoy(data){this.decoys.push({...data,maxLife:data.life,decoy:true});}
getNearestEnemies(point,count=1,maxDistance=Infinity,predicate=()=>true){return this.enemies.filter((e)=>!e.dead&&predicate(e)).map((e)=>({e,d:distance(point,e)})).filter((x)=>x.d<=maxDistance).sort((a,b)=>a.d-b.d).slice(0,count).map((x)=>x.e);}
damageEnemiesInCircle(source,radius,damage,extra={}){for(const enemy of this.enemies){if(enemy.dead||distance(source,enemy)>radius+enemy.radius)continue;const result=enemy.receiveHit(this,{damage,source:{x:source.x,y:source.y},stagger:extra.stagger||.12,knockback:extra.knockback||1,type:extra.type||'area',owner:extra.type});if(result.applied){this.player.gainOverdrive(result.damage*.2);if(result.killed)this.registerKill(enemy,extra.type||'area');}}}}
