import { add, circleHit, clamp, distance, fromAngle, normalize, pick, rotate, seededRng, segmentPointDistanceSq, shuffle, sub } from './core.js';
import { BASE_DIALOGUE, DUO_MODULES, MODULES, REWARD_TYPES, ROOM_TEMPLATES } from './data.js';

const COMBAT_REWARDS=['weapon','mobility','ordnance','overdrive','defense','credits','permanent'];
const chooseReward=(rng,used=[])=>{const pool=COMBAT_REWARDS.filter((id)=>!used.includes(id));return pick(pool.length?pool:COMBAT_REWARDS,rng);};
const chooseTemplate=(rng,history,elite=false)=>{const recent=history.slice(-2);const pool=ROOM_TEMPLATES.filter((t)=>!t.boss&&Boolean(t.elite)===elite&&!recent.includes(t.id));return pick(pool.length?pool:ROOM_TEMPLATES.filter((t)=>!t.boss&&Boolean(t.elite)===elite),rng);};
export function generateRoomGraph(seed=Date.now(),length=10){const rng=seededRng(seed),nodes=[];let previousTemplateIds=[];for(let depth=0;depth<length;depth+=1){if(depth===length-1){nodes.push({depth,choices:[{id:`${depth}-boss`,type:'combat',boss:true,reward:'permanent',template:'boss_alpha'}]});continue;}if(depth===4){nodes.push({depth,choices:[{id:`${depth}-shop`,type:'shop',reward:'credits'},{id:`${depth}-repair`,type:'repair',reward:'repair'}]});continue;}if(depth===7){const a=chooseTemplate(rng,previousTemplateIds,true),b=chooseTemplate(rng,[...previousTemplateIds,a.id],true);nodes.push({depth,choices:[{id:`${depth}-a`,type:'combat',elite:true,reward:chooseReward(rng),template:a.id},{id:`${depth}-b`,type:'combat',elite:true,reward:chooseReward(rng),template:b.id}]});previousTemplateIds.push(a.id,b.id);continue;}if(depth===2||depth===6){const t=chooseTemplate(rng,previousTemplateIds,false);nodes.push({depth,choices:shuffle([{id:`${depth}-event`,type:'event',reward:'permanent'},{id:`${depth}-combat`,type:'combat',reward:chooseReward(rng),template:t.id}],rng)});previousTemplateIds.push(t.id);continue;}const a=chooseTemplate(rng,previousTemplateIds,false),b=chooseTemplate(rng,[...previousTemplateIds,a.id],false),ra=chooseReward(rng),rb=chooseReward(rng,[ra]);nodes.push({depth,choices:[{id:`${depth}-a`,type:'combat',reward:ra,template:a.id},{id:`${depth}-b`,type:'combat',reward:rb,template:b.id}]});previousTemplateIds.push(a.id,b.id);}return{seed,length,nodes};}
export function describeRoomChoice(choice){if(choice.type==='shop')return{name:'军械补给舰',detail:'购买模块、修理并重整构筑',icon:'▣',color:'#ffd269'};if(choice.type==='repair')return{name:'紧急维修区',detail:'恢复耐久并补充一次推进储能',icon:'✚',color:'#76ffe1'};if(choice.type==='event')return{name:'未知信号',detail:'一次带有代价的战场事件',icon:'?',color:'#c79aff'};const t=ROOM_TEMPLATES.find((x)=>x.id===choice.template),r=REWARD_TYPES[choice.reward];return{name:choice.boss?'区域首领：守墓者·阿尔法':t?.name||'战斗房间',detail:`${choice.elite?'精英战 · ':''}${r?.name||'战斗奖励'}`,icon:choice.boss?'☠':r?.icon||'◇',color:r?.color||'#fff'};}
const ownedTags=(run)=>new Set([...(run.mechTags||[]),...run.modules.flatMap((m)=>m.tags||[])]);
export function getEligibleDuoModules(run){const tags=ownedTags(run);return DUO_MODULES.filter((m)=>m.requires.every((tag)=>tags.has(tag))&&!run.modules.some((x)=>x.id===m.id));}
export function rollModuleChoices(run,rewardType='weapon',seed=Date.now(),count=3){const rng=seededRng(seed),slots=REWARD_TYPES[rewardType]?.slots||[],existing=new Set(run.modules.map((m)=>m.id)),eligibleDuo=getEligibleDuoModules(run),basePool=MODULES.filter((m)=>!existing.has(m.id)&&(!slots.length||slots.includes(m.slot))),rarePool=basePool.filter((m)=>m.rarity==='rare'),commonPool=basePool.filter((m)=>m.rarity==='common'),picks=[];if(eligibleDuo.length&&rng()<.35)picks.push(shuffle(eligibleDuo,rng)[0]);while(picks.length<count){const useRare=rng()<.32&&rarePool.length,source=useRare?rarePool:(commonPool.length?commonPool:basePool),candidate=shuffle(source.filter((m)=>!picks.some((p)=>p.id===m.id)),rng)[0];if(!candidate)break;picks.push(candidate);}return picks;}
export function applyModuleEffects(stats,module){const next=structuredClone(stats);next.effects||={};for(const[key,value]of Object.entries(module.effects||{})){if(key.endsWith('Mul')){const k=key.slice(0,-3);next[k]=(next[k]??1)*value;}else if(key.endsWith('Add')){const k=key.slice(0,-3);next[k]=(next[k]??0)+value;}else if(typeof value==='number'&&typeof next.effects[key]==='number')next.effects[key]+=value;else next.effects[key]=value;}return next;}
export function buildRunStats(mech,modules=[]){let stats={...mech.stats,effects:{}};for(const module of modules)stats=applyModuleEffects(stats,module);stats.maxHp=Math.round(stats.maxHp);stats.primaryDamage=Math.round(stats.primaryDamage*10)/10;stats.secondaryDamage=Math.round(stats.secondaryDamage*10)/10;stats.ordnanceDamage=Math.round(stats.ordnanceDamage*10)/10;return stats;}
const PROFILE_KEY='mecha-marco-profile-v4';
export const DEFAULT_PROFILE={version:4,runs:0,victories:0,permanent:0,selectedMech:'vanguard',unlockedMechs:['vanguard','bulwark','starwing'],seenDialogue:{},dialogueCooldowns:{},history:[],settings:{renderScale:1,vibration:true,aimAssist:.22,audio:.65}};
export function sanitizeProfile(raw){const p={...DEFAULT_PROFILE,...(raw||{})};p.settings={...DEFAULT_PROFILE.settings,...(raw?.settings||{})};p.unlockedMechs=Array.from(new Set(Array.isArray(p.unlockedMechs)?p.unlockedMechs:DEFAULT_PROFILE.unlockedMechs));p.history=Array.isArray(p.history)?p.history.slice(-20):[];p.seenDialogue=p.seenDialogue&&typeof p.seenDialogue==='object'?p.seenDialogue:{};p.dialogueCooldowns=p.dialogueCooldowns&&typeof p.dialogueCooldowns==='object'?p.dialogueCooldowns:{};return p;}
export function loadProfile(storage=globalThis.localStorage){try{const raw=storage?.getItem(PROFILE_KEY);return sanitizeProfile(raw?JSON.parse(raw):null);}catch{return sanitizeProfile(null);}}
export function saveProfile(profile,storage=globalThis.localStorage){const clean=sanitizeProfile(profile);try{storage?.setItem(PROFILE_KEY,JSON.stringify(clean));}catch{}return clean;}
export function recordRun(profile,report){const next=sanitizeProfile(profile);next.runs+=1;if(report.victory)next.victories+=1;next.permanent+=report.permanentEarned||0;next.history.push({...report,at:Date.now()});next.history=next.history.slice(-20);for(const key of Object.keys(next.dialogueCooldowns))next.dialogueCooldowns[key]=Math.max(0,next.dialogueCooldowns[key]-1);return next;}
export function selectDialogue(profile,lastRun){return BASE_DIALOGUE.filter((d)=>!(d.once&&profile.seenDialogue[d.id])&&!((profile.dialogueCooldowns[d.id]||0)>0)&&d.when(profile,lastRun)).sort((a,b)=>b.priority-a.priority)[0]||BASE_DIALOGUE.at(-1);}
export function markDialogue(profile,dialogue){const next=structuredClone(profile);next.seenDialogue[dialogue.id]=(next.seenDialogue[dialogue.id]||0)+1;if(dialogue.cooldown)next.dialogueCooldowns[dialogue.id]=dialogue.cooldown;return next;}
const localPoint=(root,yaw,x,y)=>add(root,rotate({x,y},yaw));
export function computeMechRig(actor,time=0){const root={x:actor.x,y:actor.y},yaw=actor.aim??actor.yaw??0,stride=Math.sin(time*12+(actor.id||0))*Math.min(1,actor.speed01||0)*.16,recoil=actor.primaryKick||0,hit=actor.hitVisual||{back:0,side:0},torsoYaw=yaw+(hit.side||0)*.12,bodyShift=rotate({x:-(hit.back||0)*.16,y:(hit.side||0)*.08},yaw),body=add(root,bodyShift),shoulderR=localPoint(body,torsoYaw,.15,.55),shoulderL=localPoint(body,torsoYaw,.15,-.55),primaryAim=yaw+(actor.primarySpreadVisual||0),forearmR=add(shoulderR,fromAngle(primaryAim,.66-recoil*.13)),rifleBase=add(forearmR,fromAngle(primaryAim,.18)),muzzle=add(rifleBase,fromAngle(primaryAim,.92));let saberAngle=yaw-.28,saberReach=.72;const saberPhase=actor.saberPhase||0;if(saberPhase>0){const t=Math.min(1,saberPhase),eased=1-(1-t)**3;saberAngle=yaw-2.1+eased*3.6;saberReach=.92+Math.sin(t*Math.PI)*.25;}const forearmL=add(shoulderL,fromAngle(saberAngle,.58)),saberBase=add(forearmL,fromAngle(saberAngle,.18)),saberTip=add(saberBase,fromAngle(saberAngle,saberReach)),hipR=localPoint(body,torsoYaw,-.28,.28),hipL=localPoint(body,torsoYaw,-.28,-.28),legAngleR=torsoYaw+.03+stride,legAngleL=torsoYaw-.03-stride,kneeR=add(hipR,fromAngle(legAngleR+Math.PI,.48)),kneeL=add(hipL,fromAngle(legAngleL+Math.PI,.48)),footR=add(kneeR,fromAngle(legAngleR+Math.PI,.48)),footL=add(kneeL,fromAngle(legAngleL+Math.PI,.48)),backpack=localPoint(body,torsoYaw,-.36,0),missileL=localPoint(backpack,torsoYaw,-.12,-.52),missileR=localPoint(backpack,torsoYaw,-.12,.52),thrusterL=localPoint(backpack,torsoYaw,-.58,-.3),thrusterR=localPoint(backpack,torsoYaw,-.58,.3),head=localPoint(body,torsoYaw,.52,0),wingL=localPoint(backpack,torsoYaw,-.15,-.78),wingR=localPoint(backpack,torsoYaw,-.15,.78);return{root,body,yaw,torsoYaw,head,shoulderR,shoulderL,forearmR,forearmL,rifleBase,muzzle,saberBase,saberTip,saberAngle,hipR,hipL,kneeR,kneeL,footR,footL,backpack,missileL,missileR,thrusterL,thrusterR,wingL,wingR,nodes:{muzzle,saberBase,saberTip,missileL,missileR,thrusterL,thrusterR}};}
export function sampleSaberSweep(actor,samples=9){const original=actor.saberPhase,points=[];for(let i=0;i<samples;i+=1){actor.saberPhase=i/(samples-1);points.push(computeMechRig(actor).saberTip);}actor.saberPhase=original;return points;}
export function verifyRigAlignment(actor){const rig=computeMechRig(actor),forward=fromAngle(actor.aim||0,1),v={x:rig.muzzle.x-rig.rifleBase.x,y:rig.muzzle.y-rig.rifleBase.y},muzzleDot=v.x*forward.x+v.y*forward.y,lateral=Math.abs(v.x*forward.y-v.y*forward.x);return{muzzleForward:muzzleDot>.7,muzzleLateralError:lateral,saberLength:Math.hypot(rig.saberTip.x-rig.saberBase.x,rig.saberTip.y-rig.saberBase.y)};}
export function projectileHitsActor(projectile,actor){return!actor.dead&&circleHit(projectile,projectile.radius||.12,actor,actor.radius||.6);}
export function saberHitsActor(base,tip,width,actor){return!actor.dead&&segmentPointDistanceSq(base,tip,actor)<=(width+(actor.radius||.6))**2;}
export function applyDirectionalHit(actor,hit){if(actor.dead||actor.invulnerable>0)return{applied:false,damage:0};const source=hit.source||{x:actor.x-1,y:actor.y},incoming=normalize(sub(actor,source)),forward=fromAngle(actor.aim??actor.yaw??0),side=clamp(forward.x*incoming.y-forward.y*incoming.x,-1,1),front=clamp(forward.x*incoming.x+forward.y*incoming.y,-1,1),armor=clamp(actor.armor||0,0,.8),markedMul=actor.markTime>0?1+(actor.markAmount||0):1,damage=Math.round(Math.max(1,hit.damage*(1-armor)*markedMul)*10)/10,resist=clamp(actor.staggerResist||0,0,.9);actor.hp=Math.max(0,actor.hp-damage);actor.hitStun=Math.max(actor.hitStun||0,(hit.stagger||.12)*(1-resist));actor.hitVisual={back:Math.max(actor.hitVisual?.back||0,Math.max(0,front)*(hit.force||1)),side:side*(hit.force||1)};actor.vx=(actor.vx||0)+incoming.x*(hit.knockback||0)*(1-resist);actor.vy=(actor.vy||0)+incoming.y*(hit.knockback||0)*(1-resist);if(hit.mark){actor.markTime=hit.mark.duration;actor.markAmount=hit.mark.amount;}actor.lastHitType=hit.type||'generic';actor.lastHitSource=source;if(actor.hp<=0)actor.dead=true;return{applied:true,damage,killed:actor.dead,side,front};}
export function nearestActor(point,actors,maxDistance=Infinity,predicate=()=>true){let best=null,bestDistance=maxDistance;for(const actor of actors){if(actor.dead||!predicate(actor))continue;const d=distance(point,actor);if(d<bestDistance){bestDistance=d;best=actor;}}return best;}
export class AbilitySystem{constructor(){this.cooldowns=new Map();this.buffer=new Map();}tick(dt){for(const[key,value]of this.cooldowns)this.cooldowns.set(key,Math.max(0,value-dt));for(const[key,value]of this.buffer){const next=value-dt;if(next<=0)this.buffer.delete(key);else this.buffer.set(key,next);}}ready(id){return(this.cooldowns.get(id)||0)<=0;}setCooldown(id,value){this.cooldowns.set(id,Math.max(0,value));}request(id,duration=.15){this.buffer.set(id,Math.max(duration,this.buffer.get(id)||0));}consume(id,canUse=true){if(!canUse||!this.buffer.has(id))return false;this.buffer.delete(id);return true;}clear(){this.cooldowns.clear();this.buffer.clear();}}