import { clamp, length, normalize } from '../core.js';
const ACTIONS=['primary','secondary','dash','ordnance','overdrive','pause'];
export class InputRouter{
constructor(canvas,touchRoot){this.canvas=canvas;this.touchRoot=touchRoot;this.keys=new Set();this.held=Object.fromEntries(ACTIONS.map((a)=>[a,false]));this.pressed=Object.fromEntries(ACTIONS.map((a)=>[a,false]));this.move={x:0,y:0};this.aim={x:0,y:-1};this.mouse={x:0,y:0,active:false};this.touch={move:null,aim:null};this.touchMode=matchMedia('(pointer:coarse)').matches||navigator.maxTouchPoints>0;this.enabled=true;this.bind();}
bind(){addEventListener('keydown',(e)=>{this.keys.add(e.code);if(e.code==='Escape')this.press('pause');if(['Space','KeyQ','KeyE'].includes(e.code))e.preventDefault();},{passive:false});addEventListener('keyup',(e)=>this.keys.delete(e.code));addEventListener('blur',()=>this.clear());this.canvas.addEventListener('pointermove',(e)=>{if(this.touchMode||!this.enabled)return;const r=this.canvas.getBoundingClientRect();this.mouse.x=e.clientX-r.left;this.mouse.y=e.clientY-r.top;this.mouse.active=true;});this.canvas.addEventListener('pointerdown',(e)=>{if(this.touchMode||!this.enabled)return;if(e.button===0)this.setHeld('primary',true,true);if(e.button===2)this.setHeld('secondary',true,true);});addEventListener('pointerup',(e)=>{if(this.touchMode)return;if(e.button===0)this.setHeld('primary',false);if(e.button===2)this.setHeld('secondary',false);});this.canvas.addEventListener('contextmenu',(e)=>e.preventDefault());if(this.touchRoot){for(const stick of this.touchRoot.querySelectorAll('[data-stick]'))this.bindStick(stick,stick.dataset.stick);for(const button of this.touchRoot.querySelectorAll('[data-action]'))this.bindActionButton(button,button.dataset.action);}}
bindStick(element,kind){const knob=element.querySelector('.stick-knob'),state={pointerId:null,center:{x:0,y:0},value:{x:0,y:0}},update=(e)=>{const r=element.getBoundingClientRect();state.center={x:r.left+r.width/2,y:r.top+r.height/2};const dx=e.clientX-state.center.x,dy=e.clientY-state.center.y,max=r.width*.34,mag=Math.hypot(dx,dy)||1,scale=Math.min(1,max/mag),px=dx*scale,py=dy*scale;knob.style.transform=`translate(${px}px,${py}px)`;state.value={x:clamp(dx/max,-1,1),y:clamp(dy/max,-1,1)};if(length(state.value)>1)state.value=normalize(state.value);if(kind==='move')this.move=state.value;else{this.aim=state.value;if(length(state.value)>.5)this.setHeld('primary',true,true);else this.setHeld('primary',false);}};element.addEventListener('pointerdown',(e)=>{if(!this.enabled||state.pointerId!==null)return;state.pointerId=e.pointerId;element.setPointerCapture(e.pointerId);update(e);e.preventDefault();},{passive:false});element.addEventListener('pointermove',(e)=>{if(e.pointerId!==state.pointerId)return;update(e);e.preventDefault();},{passive:false});const end=(e)=>{if(e.pointerId!==state.pointerId)return;state.pointerId=null;state.value={x:0,y:0};knob.style.transform='translate(0,0)';if(kind==='move')this.move={x:0,y:0};else this.setHeld('primary',false);};element.addEventListener('pointerup',end);element.addEventListener('pointercancel',end);this.touch[kind]=state;}
bindActionButton(button,action){const end=(e)=>{this.setHeld(action,false);button.classList.remove('active');e.preventDefault();};button.addEventListener('pointerdown',(e)=>{if(!this.enabled)return;button.setPointerCapture(e.pointerId);this.setHeld(action,true,true);button.classList.add('active');e.preventDefault();},{passive:false});button.addEventListener('pointerup',end,{passive:false});button.addEventListener('pointercancel',end,{passive:false});}
setHeld(action,value,alsoPress=false){if(!(action in this.held))return;if(value&&!this.held[action]&&alsoPress)this.pressed[action]=true;this.held[action]=value;}
press(action){if(action in this.pressed)this.pressed[action]=true;}
update(screenToWorld,player){if(!this.enabled){this.move={x:0,y:0};return this.snapshot();}if(!this.touchMode){const x=(this.keys.has('KeyD')||this.keys.has('ArrowRight')?1:0)-(this.keys.has('KeyA')||this.keys.has('ArrowLeft')?1:0),y=(this.keys.has('KeyS')||this.keys.has('ArrowDown')?1:0)-(this.keys.has('KeyW')||this.keys.has('ArrowUp')?1:0);this.move=length({x,y})>1?normalize({x,y}):{x,y};if(this.mouse.active&&player){const world=screenToWorld(this.mouse.x,this.mouse.y);this.aim=normalize({x:world.x-player.x,y:world.y-player.y});}this.setHeld('dash',this.keys.has('Space'),this.keys.has('Space'));if(this.keys.has('KeyQ'))this.setHeld('ordnance',true,true);else this.setHeld('ordnance',false);if(this.keys.has('KeyE'))this.setHeld('overdrive',true,true);else this.setHeld('overdrive',false);}return this.snapshot();}
snapshot(){const out={move:{...this.move},aim:{...this.aim},held:{...this.held},pressed:{...this.pressed},touchMode:this.touchMode};for(const action of ACTIONS)this.pressed[action]=false;return out;}
clear(){this.keys.clear();this.move={x:0,y:0};for(const action of ACTIONS){this.held[action]=false;this.pressed[action]=false;}for(const state of Object.values(this.touch)){if(!state)continue;state.pointerId=null;state.value={x:0,y:0};}for(const knob of this.touchRoot?.querySelectorAll('.stick-knob')||[])knob.style.transform='translate(0,0)';for(const button of this.touchRoot?.querySelectorAll('.active')||[])button.classList.remove('active');}
setEnabled(value){this.enabled=Boolean(value);if(!this.enabled)this.clear();}}
