import { clamp } from '../core/math.js';
import { computeMechRig } from '../combat/hardpointRig.js';
import { getVisualDesign } from './mechDesigns41.js';
import { tone,motion,project,poly,prism,segment,joint,line,line2,glow,shadow } from './mechMeshPrimitives41.js';

function head(r,a,m,d,k){const{colors:c,body:b,silhouette:s}=d;prism(r,a,m,{f:.18,z:2.08,l:.48,w:b.head*1.55,h:.42,front:.62,back:1.08,top:.82,skew:.04},c.armor,k,{stroke:tone(c.trim,1,.52),panel:false});prism(r,a,m,{f:.39,z:2.08,l:.22,w:b.head*1.15,h:.18,front:.45,back:1,top:.7},c.frame,k,{panel:false});line(r,a,m,{f:.48,s:-b.head*.42,z:2.13},{f:.5,s:b.head*.42,z:2.13},c.visor,2.2,k,1);if(['assault','interceptor','lancer'].includes(s)){line(r,a,m,{f:.25,z:2.28},{f:.48,z:2.55},c.trim,2,k,.95);line(r,a,m,{f:.34,z:2.3},{f:.48,s:-.18,z:2.44},c.trim,1.35,k,.8);line(r,a,m,{f:.34,z:2.3},{f:.48,s:.18,z:2.44},c.trim,1.35,k,.8)}if(['fortress','siege','overlord'].includes(s)){for(const side of[-1,1])prism(r,a,m,{f:.12,s:side*b.head*.62,z:2.12,l:.36,w:.12,h:.28,angle:-side*.05},c.armor2,k,{panel:false})}}

function torso(r,a,m,d,k){const{colors:c,body:b,silhouette:s}=d;prism(r,a,m,{f:.02,z:1.36,l:b.length,w:b.chest,h:.66,front:.62,back:1.16,top:.84,skew:.08},c.armor,k,{stroke:tone(c.trim,1,.46)});prism(r,a,m,{f:.34,z:1.48,l:.62,w:b.chest*.68,h:.3,front:.48,back:1.04,top:.78,skew:.08},c.armor2,k,{stroke:tone(c.trim,1,.38)});prism(r,a,m,{f:-.45,z:1.24,l:.38,w:b.waist,h:.42,front:.76,back:1.1,top:.82},c.frame,k,{panel:false});prism(r,a,m,{f:-.72,z:.9,l:.46,w:b.waist*1.35,h:.42,front:.78,back:1.12,top:.84},c.armor2,k,{panel:false});glow(r,a,m,{f:.48,z:1.53},.17,c.glow,k,.72);for(const side of[-1,1])line(r,a,m,{f:.07,s:side*b.chest*.33,z:1.64},{f:.52,s:side*b.chest*.18,z:1.51},c.accent,1.45,k,.84);if(['fortress','bulwark','overlord'].includes(s)){for(const side of[-1,1])prism(r,a,m,{f:-.04,s:side*b.chest*.62,z:1.52,l:.8,w:.28,h:.48,angle:-side*.08,front:.72,back:1.06},c.armor2,k,{panel:false})}if(s==='interceptor'){for(const side of[-1,1])prism(r,a,m,{f:-.12,s:side*b.chest*.54,z:1.55,l:.9,w:.14,h:.22,angle:-side*.18,front:.42,back:1.1},c.trim,k,{panel:false,alpha:.88,glow:c.glow})}}

function backpack(r,a,m,d,k){const{colors:c,silhouette:s}=d;prism(r,a,m,{f:-.55,z:1.42,l:.72,w:.78,h:.42,front:.94,back:1.04,top:.88},c.frame,k,{panel:false});if(s==='interceptor'){for(const side of[-1,1]){prism(r,a,m,{f:-.55,s:side*.73,z:1.48,l:1.45,w:.2,h:.2,angle:side*.34,front:.3,back:1.2,top:.62},c.armor2,k,{panel:false,stroke:tone(c.trim,1,.45)});prism(r,a,m,{f:-.82,s:side*.92,z:1.34,l:1.05,w:.14,h:.16,angle:side*.52,front:.2,back:1.25,top:.55},c.trim,k,{panel:false,alpha:.85,glow:c.glow})}}else if(['fortress','siege','overlord'].includes(s)){for(const side of[-1,1]){prism(r,a,m,{f:-.73,s:side*.48,z:1.48,l:.92,w:.3,h:.56,front:.72,back:1.08},c.metal,k,{panel:false});glow(r,a,m,{f:-1.1,s:side*.48,z:1.43},.16,c.glow,k,.6)}}else for(const side of[-1,1]){prism(r,a,m,{f:-.72,s:side*.4,z:1.42,l:.74,w:.22,h:.3,front:.62,back:1.12},c.metal,k,{panel:false});glow(r,a,m,{f:-1.02,s:side*.4,z:1.4},.12,c.glow,k,.58)}}

function legPoints(d,m,side){const b=d.body,step=m.stride*side;return{hip:{f:-.55,s:side*b.waist*.62,z:.78},knee:{f:-.2+step*.18,s:side*(b.leg+.04),z:.36},ankle:{f:.12+step*.38,s:side*(b.leg+.02),z:.07},foot:{f:.42+step*.44,s:side*(b.leg+.02),z:.02}}}
function leg(r,a,m,d,k,side,far){const{colors:c,body:b,silhouette:s}=d,p=legPoints(d,m,side);joint(r,a,m,p.hip,.11,c.frame,k);segment(r,a,m,p.hip,p.knee,b.leg,c.armor2,k,{panel:false,alpha:far?.82:1});joint(r,a,m,p.knee,.105,c.metal,k,c.glow);segment(r,a,m,p.knee,p.ankle,b.calf,c.armor,k,{stroke:tone(c.trim,1,.36),alpha:far?.84:1});prism(r,a,m,{f:p.foot.f,s:p.foot.s,z:.08,l:s==='fortress'?.72:.58,w:b.calf*1.12,h:.2,front:.45,back:1.1,top:.8},c.frame,k,{panel:false,alpha:far?.82:1});line(r,a,m,{f:p.knee.f+.08,s:p.knee.s,z:p.knee.z+.11},{f:p.ankle.f+.05,s:p.ankle.s,z:p.ankle.z+.12},c.accent,1.1,k,far?.42:.74);if(s==='interceptor')glow(r,a,m,{f:p.ankle.f-.08,s:p.ankle.s,z:p.ankle.z+.14},.1,c.glow,k,.5)}

function armPoints(d,m,side){const b=d.body;let hand={f:.77-m.recoil,s:side*b.shoulder*.72,z:1.04};if(side>0&&m.saber>0){const arc=(m.saber-.5)*Math.PI*1.4;hand={f:.34+Math.cos(arc)*.72,s:side*.2+Math.sin(arc)*.72,z:1.12+Math.sin(m.saber*Math.PI)*.12}}return{shoulder:{f:.06,s:side*b.shoulder,z:1.58},elbow:{f:.42,s:side*b.shoulder*.88,z:1.3},hand}}
function arm(r,a,m,d,k,side,far){const{colors:c,body:b,silhouette:s}=d,p=armPoints(d,m,side),wide=['fortress','overlord'].includes(s)?.48:.34;prism(r,a,m,{f:p.shoulder.f-.03,s:p.shoulder.s,z:p.shoulder.z,l:.54,w:wide,h:.42,angle:side*.08,front:.58,back:1.08,top:.8},c.armor,k,{panel:false,alpha:far?.82:1,stroke:tone(c.trim,1,.36)});joint(r,a,m,p.shoulder,.11,c.frame,k);segment(r,a,m,p.shoulder,p.elbow,b.leg*.72,c.frame,k,{panel:false,alpha:far?.8:1});joint(r,a,m,p.elbow,.095,c.metal,k);segment(r,a,m,p.elbow,p.hand,b.leg*.82,c.armor2,k,{panel:false,alpha:far?.82:1});if(side<0&&['fortress','bulwark'].includes(s))prism(r,a,m,{f:p.hand.f-.05,s:p.hand.s-.08,z:p.hand.z,l:.7,w:.34,h:.48,front:.72,back:1.06},c.armor,k,{panel:false,stroke:tone(c.trim,1,.4)})}

function rifle(r,a,d,k){const c=d.colors,rig=computeMechRig(a,performance.now()/1000),x=r.worldToScreen(rig.rifleBase.x,rig.rifleBase.y),y=r.worldToScreen(rig.muzzle.x,rig.muzzle.y),dx=y.x-x.x,dy=y.y-x.y,len=Math.hypot(dx,dy)||1,nx=-dy/len,ny=dx/len,w=(['fortress','siege'].includes(d.silhouette)?8.2:5.8)*r.dpr*k,body=[{x:x.x+nx*w,y:x.y+ny*w},{x:y.x-dx*.1+nx*w*.72,y:y.y-dy*.1+ny*w*.72},{x:y.x+nx*w*.35,y:y.y+ny*w*.35},{x:y.x-nx*w*.35,y:y.y-ny*w*.35},{x:y.x-dx*.1-nx*w*.72,y:y.y-dy*.1-ny*w*.72},{x:x.x-nx*w,y:x.y-ny*w}];poly(r.ctx,body,tone(c.frame,.78),tone(c.trim,1,.62),1.1*r.dpr,{color:c.glow,blur:(a.primaryKick||0)*12*r.dpr});poly(r.ctx,body.map((p,i)=>i<3?{x:p.x-dx*.03,y:p.y-dy*.03}:p),tone(c.armor2,1.02,.92),tone(c.armor,1,.5),.7*r.dpr);line2(r.ctx,{x:x.x+dx*.22,y:x.y+dy*.22},{x:y.x-dx*.25,y:y.y-dy*.25},c.accent,1.3*r.dpr,.76);r.ctx.save();r.ctx.fillStyle='#fff';r.ctx.shadowColor=c.glow;r.ctx.shadowBlur=12*r.dpr*(a.primaryKick||0);r.ctx.beginPath();r.ctx.arc(y.x,y.y,2.8*r.dpr*k,0,Math.PI*2);r.ctx.fill();r.ctx.restore()}

function saber(r,a,d,k){const c=d.colors,rig=computeMechRig(a,performance.now()/1000),x=r.worldToScreen(rig.saberBase.x,rig.saberBase.y),y=r.worldToScreen(rig.saberTip.x,rig.saberTip.y),dx=y.x-x.x,dy=y.y-x.y,len=Math.hypot(dx,dy)||1,nx=-dy/len,ny=dx/len,h=4.2*r.dpr*k;poly(r.ctx,[{x:x.x+nx*h,y:x.y+ny*h},{x:x.x+dx*.22+nx*h*.55,y:x.y+dy*.22+ny*h*.55},{x:x.x+dx*.22-nx*h*.55,y:x.y+dy*.22-ny*h*.55},{x:x.x-nx*h,y:x.y-ny*h}],tone(c.frame,.72),tone(c.trim,1,.6),r.dpr);if((a.saberPhase||0)>0){const q=r.ctx;q.save();q.globalCompositeOperation='lighter';q.lineCap='round';q.shadowColor=c.glow;q.shadowBlur=20*r.dpr;q.strokeStyle=tone(c.glow,1,.38);q.lineWidth=15*r.dpr*k;q.beginPath();q.moveTo(x.x+dx*.18,x.y+dy*.18);q.lineTo(y.x,y.y);q.stroke();q.strokeStyle=c.glow;q.lineWidth=5.8*r.dpr*k;q.stroke();q.strokeStyle='#fff';q.lineWidth=1.8*r.dpr;q.stroke();q.restore()}}

function thrusters(r,a,m,d,k){if((a.speed01||0)<.08&&a.dashTimer<=0&&a.overdriveTimer<=0)return;const p=a.dashTimer>0?1.8:a.overdriveTimer>0?1.35:.72+(a.speed01||0)*.34;for(const side of[-1,1]){const x=project(r,a,{f:-1.02,s:side*.34,z:1.38},m,k),y=project(r,a,{f:-1.02-.55*p,s:side*.34,z:1.36},m,k),c=r.ctx;c.save();c.globalCompositeOperation='lighter';c.lineCap='round';c.shadowColor=d.colors.glow;c.shadowBlur=16*r.dpr;c.strokeStyle=tone(d.colors.glow,1,.48);c.lineWidth=11*r.dpr*k;c.beginPath();c.moveTo(x.x,x.y);c.lineTo(y.x,y.y);c.stroke();c.strokeStyle='#fff';c.lineWidth=2.2*r.dpr;c.stroke();c.restore()}}

function health(r,a,k){const p=r.worldToScreen(a.x,a.y-.95*k),w=48*r.dpr*k,ratio=clamp(a.hp/a.maxHp,0,1),c=r.ctx;c.save();c.fillStyle='rgba(3,7,16,.74)';c.fillRect(p.x-w/2,p.y,w,4*r.dpr);c.fillStyle=a.boss?'#ff4b91':a.elite?'#ff9e56':'#ff6576';c.fillRect(p.x-w/2,p.y,w*ratio,4*r.dpr);c.restore()}

function draw41(r,a,isPlayer,time){const d=getVisualDesign(a,isPlayer),m=motion(a,time,clamp),k=d.scale*(a.boss?1.18:a.elite?1.06:1)*(1-(a.spawn||0)*.22),alpha=clamp(1-(a.spawn||0)*1.55,0,1),c=r.ctx;shadow(r,a,k);c.save();c.globalAlpha=alpha;if(a.hitStun>0)c.filter='brightness(1.65) saturate(.65) contrast(1.15)';backpack(r,a,m,d,k);const near=Math.cos(a.yaw||0)>0?-1:1;leg(r,a,m,d,k,-near,true);arm(r,a,m,d,k,-near,true);torso(r,a,m,d,k);leg(r,a,m,d,k,near,false);arm(r,a,m,d,k,near,false);head(r,a,m,d,k);for(const side of[-1,1])line(r,a,m,{f:-.16,s:side*.18,z:1.27},{f:-.38,s:side*.14,z:1.02},tone(d.colors.trim,1,.7),.8,k,.65);thrusters(r,a,m,d,k);rifle(r,a,d,k);saber(r,a,d,k);c.restore();if(!isPlayer)health(r,a,k)}

export function applyMechVisual41(Renderer){if(Renderer.__mechVisual41Applied)return;Renderer.__mechVisual41Applied=true;Renderer.prototype.drawMech=function(a,isPlayer,time){draw41(this,a,isPlayer,time)}}
