const rgb=(hex)=>{const v=String(hex||'#fff').replace('#',''),f=v.length===3?v.split('').map(c=>c+c).join(''):v.padEnd(6,'f').slice(0,6);return[parseInt(f.slice(0,2),16),parseInt(f.slice(2,4),16),parseInt(f.slice(4,6),16)]};
export const tone=(hex,a=1,alpha=1)=>{const c=rgb(hex),m=a>=1?255:0,t=a>=1?Math.min(1,a-1):Math.min(1,1-a),o=c.map(x=>Math.round(x+(m-x)*t));return`rgba(${o[0]},${o[1]},${o[2]},${alpha})`};
const rot=(f,s,a)=>({f:f*Math.cos(a)-s*Math.sin(a),s:f*Math.sin(a)+s*Math.cos(a)});
export function motion(actor,time,clamp){const speed=clamp(actor.speed01||0,0,1),phase=time*8.4+(actor.id||0)*.37;return{speed,stride:Math.sin(phase)*speed,bob:Math.abs(Math.sin(phase))*.055*speed,back:(actor.hitVisual?.back||0)*.12,side:(actor.hitVisual?.side||0)*.1,recoil:(actor.primaryKick||0)*.12,saber:actor.saberPhase||0}};
export function project(r,a,p,m,k=1){const f=(p.f-m.back)*k,s=(p.s+m.side)*k,yaw=a.yaw??a.aim??0,wx=a.x+Math.cos(yaw)*f-Math.sin(yaw)*s,wy=a.y+Math.sin(yaw)*f+Math.cos(yaw)*s,q=r.worldToScreen(wx,wy);return{x:q.x,y:q.y-(p.z+m.bob)*r.scale*.54*k,d:wy+p.z*.16}};
export function poly(ctx,pts,fill,stroke='rgba(230,245,255,.24)',w=1,glow=null){if(pts.length<3)return;ctx.save();if(glow){ctx.shadowColor=glow.color;ctx.shadowBlur=glow.blur}ctx.fillStyle=fill;ctx.strokeStyle=stroke;ctx.lineWidth=w;ctx.beginPath();ctx.moveTo(pts[0].x,pts[0].y);for(let i=1;i<pts.length;i++)ctx.lineTo(pts[i].x,pts[i].y);ctx.closePath();ctx.fill();if(w)ctx.stroke();ctx.restore()}
function vertices(part){const{f=0,s=0,z=0,l=.5,w=.4,h=.3,angle=0,front=.82,back=1.08,top=.9,skew=0}=part,spec=[[l/2,-w*front/2,-h/2],[l/2,w*front/2,-h/2],[-l/2,-w*back/2,-h/2],[-l/2,w*back/2,-h/2],[l/2+skew,-w*front*top/2,h/2],[l/2+skew,w*front*top/2,h/2],[-l/2+skew,-w*back*top/2,h/2],[-l/2+skew,w*back*top/2,h/2]];return spec.map(([df,ds,dz])=>{const q=rot(df,ds,angle);return{f:f+q.f,s:s+q.s,z:z+dz}})}
export function prism(r,a,m,part,color,k,opt={}){const v=vertices(part).map(p=>project(r,a,p,m,k)),faces=[[[0,1,5,4],1.04],[[2,3,7,6],.62],[[0,2,6,4],.78],[[1,3,7,5],.9],[[4,5,7,6],1.2]].map(([i,shade])=>({i,shade,d:i.reduce((n,x)=>n+v[x].d,0)/i.length})).sort((x,y)=>x.d-y.d);for(const f of faces)poly(r.ctx,f.i.map(i=>v[i]),tone(color,f.shade,opt.alpha??1),opt.stroke||'rgba(225,240,255,.28)',(opt.width||1.05)*r.dpr,opt.glow?{color:opt.glow,blur:(opt.blur||5)*r.dpr}:null);if(opt.panel!==false){const p=[4,5,7,6].map(i=>v[i]),x={x:(p[0].x+p[3].x)/2,y:(p[0].y+p[3].y)/2},y={x:(p[1].x+p[2].x)/2,y:(p[1].y+p[2].y)/2};line2(r.ctx,x,y,opt.panelColor||'rgba(8,15,24,.62)',.72*r.dpr,.44)}return v}
export function segment(r,a,m,x,y,w,color,k,opt={}){const df=y.f-x.f,ds=y.s-x.s,dz=y.z-x.z;return prism(r,a,m,{f:(x.f+y.f)/2,s:(x.s+y.s)/2,z:(x.z+y.z)/2,l:Math.max(.08,Math.hypot(df,ds)),w,h:Math.max(w*.72,Math.abs(dz)+w*.35),angle:Math.atan2(ds,df),front:.84,back:1.02,top:.86},color,k,opt)}
export function joint(r,a,m,p,size,color,k,glow=null){const q=project(r,a,p,m,k),c=r.ctx;c.save();c.translate(q.x,q.y);c.scale(1,.72);c.fillStyle=tone(color,.8);c.strokeStyle=tone(color,1.35);c.lineWidth=1.1*r.dpr;if(glow){c.shadowColor=glow;c.shadowBlur=7*r.dpr}c.beginPath();c.arc(0,0,size*r.scale*k,0,Math.PI*2);c.fill();c.stroke();c.restore()}
export function line(r,a,m,x,y,color,w,k,alpha=.8){line2(r.ctx,project(r,a,x,m,k),project(r,a,y,m,k),color,w*r.dpr,alpha)}
export function line2(c,x,y,color,w,alpha=1){c.save();c.globalAlpha=alpha;c.strokeStyle=color;c.lineWidth=w;c.lineCap='round';c.beginPath();c.moveTo(x.x,x.y);c.lineTo(y.x,y.y);c.stroke();c.restore()}
export function glow(r,a,m,p,size,color,k,alpha=1){const q=project(r,a,p,m,k),px=size*r.scale*k,c=r.ctx;c.save();c.globalCompositeOperation='lighter';c.globalAlpha=alpha;const g=c.createRadialGradient(q.x,q.y,0,q.x,q.y,px);g.addColorStop(0,'rgba(255,255,255,.96)');g.addColorStop(.28,tone(color,1.15,.9));g.addColorStop(1,tone(color,1,0));c.fillStyle=g;c.beginPath();c.arc(q.x,q.y,px,0,Math.PI*2);c.fill();c.restore()}
export function shadow(r,a,k){const p=r.worldToScreen(a.x-.08,a.y+.2),c=r.ctx;c.save();c.translate(p.x,p.y);c.scale(1,.42);c.fillStyle='rgba(0,0,0,.38)';c.beginPath();c.ellipse(0,0,r.scale*.82*k,r.scale*.4*k,0,0,Math.PI*2);c.fill();c.restore()}
