const finite=(value,fallback=0)=>Number.isFinite(value)?value:fallback;
const rgb=(hex)=>{const v=String(hex||'#fff').replace('#',''),f=v.length===3?v.split('').map(c=>c+c).join(''):v.padEnd(6,'f').slice(0,6);return[parseInt(f.slice(0,2),16),parseInt(f.slice(2,4),16),parseInt(f.slice(4,6),16)]};
export const tone=(hex,a=1,alpha=1)=>{const c=rgb(hex),m=a>=1?255:0,t=a>=1?Math.min(1,a-1):Math.min(1,1-a),o=c.map(x=>Math.round(x+(m-x)*t));return`rgba(${o[0]},${o[1]},${o[2]},${finite(alpha,1)})`};
const rot=(f,s,a)=>({f:f*Math.cos(a)-s*Math.sin(a),s:f*Math.sin(a)+s*Math.cos(a)});
export function motion(actor,time,clamp){const speed=clamp(finite(actor.speed01),0,1),phase=finite(time)*8.4+finite(actor.id)*.37;return{speed,stride:Math.sin(phase)*speed,bob:Math.abs(Math.sin(phase))*.055*speed,back:finite(actor.hitVisual?.back)*.12,side:finite(actor.hitVisual?.side)*.1,recoil:finite(actor.primaryKick)*.12,saber:finite(actor.saberPhase)}};
export function project(r,a,p={},m={},k=1){const pf=finite(p.f),ps=finite(p.s),pz=finite(p.z),back=finite(m.back),side=finite(m.side),bob=finite(m.bob),scale=Math.max(.001,finite(k,1)),yaw=finite(a.yaw,finite(a.aim)),ax=finite(a.x),ay=finite(a.y),f=(pf-back)*scale,s=(ps+side)*scale,wx=ax+Math.cos(yaw)*f-Math.sin(yaw)*s,wy=ay+Math.sin(yaw)*f+Math.cos(yaw)*s,q=r.worldToScreen(wx,wy),rendererScale=Math.max(.001,finite(r.scale,1));return{x:finite(q?.x),y:finite(q?.y)-(pz+bob)*rendererScale*.54*scale,d:wy+pz*.16}};
export function poly(ctx,pts,fill,stroke='rgba(230,245,255,.24)',w=1,glow=null){const clean=pts.filter(p=>Number.isFinite(p?.x)&&Number.isFinite(p?.y));if(clean.length<3)return;ctx.save();if(glow){ctx.shadowColor=glow.color;ctx.shadowBlur=Math.max(0,finite(glow.blur))}ctx.fillStyle=fill;ctx.strokeStyle=stroke;ctx.lineWidth=Math.max(0,finite(w));ctx.beginPath();ctx.moveTo(clean[0].x,clean[0].y);for(let i=1;i<clean.length;i++)ctx.lineTo(clean[i].x,clean[i].y);ctx.closePath();ctx.fill();if(w)ctx.stroke();ctx.restore()}
function vertices(part={}){const{f=0,s=0,z=0,l=.5,w=.4,h=.3,angle=0,front=.82,back=1.08,top=.9,skew=0}=part,spec=[[l/2,-w*front/2,-h/2],[l/2,w*front/2,-h/2],[-l/2,-w*back/2,-h/2],[-l/2,w*back/2,-h/2],[l/2+skew,-w*front*top/2,h/2],[l/2+skew,w*front*top/2,h/2],[-l/2+skew,-w*back*top/2,h/2],[-l/2+skew,w*back*top/2,h/2]];return spec.map(([df,ds,dz])=>{const q=rot(df,ds,angle);return{f:f+q.f,s:s+q.s,z:z+dz}})}
export function prism(r,a,m,part,color,k,opt={}){const v=vertices(part).map(p=>project(r,a,p,m,k)),faces=[[[0,1,5,4],1.04],[[2,3,7,6],.62],[[0,2,6,4],.78],[[1,3,7,5],.9],[[4,5,7,6],1.2]].map(([i,shade])=>({i,shade,d:i.reduce((n,x)=>n+v[x].d,0)/i.length})).sort((x,y)=>x.d-y.d);for(const face of faces)poly(r.ctx,face.i.map(i=>v[i]),tone(color,face.shade,opt.alpha??1),opt.stroke||'rgba(225,240,255,.28)',(opt.width||1.05)*r.dpr,opt.glow?{color:opt.glow,blur:(opt.blur||5)*r.dpr}:null);if(opt.panel!==false){const p=[4,5,7,6].map(i=>v[i]),x={x:(p[0].x+p[3].x)/2,y:(p[0].y+p[3].y)/2},y={x:(p[1].x+p[2].x)/2,y:(p[1].y+p[2].y)/2};line2(r.ctx,x,y,opt.panelColor||'rgba(8,15,24,.62)',.72*r.dpr,.44)}return v}
export function segment(r,a,m,x={},y={},w,color,k,opt={}){const xf=finite(x.f),xs=finite(x.s),xz=finite(x.z),yf=finite(y.f),ys=finite(y.s),yz=finite(y.z),df=yf-xf,ds=ys-xs,dz=yz-xz;return prism(r,a,m,{f:(xf+yf)/2,s:(xs+ys)/2,z:(xz+yz)/2,l:Math.max(.08,Math.hypot(df,ds)),w,h:Math.max(w*.72,Math.abs(dz)+w*.35),angle:Math.atan2(ds,df),front:.84,back:1.02,top:.86},color,k,opt)}
export function joint(r,a,m,p,size,color,k,glowColor=null){const q=project(r,a,p,m,k),radius=Math.max(.001,finite(size)*Math.max(.001,finite(r.scale,1))*Math.max(.001,finite(k,1))),c=r.ctx;c.save();c.translate(q.x,q.y);c.scale(1,.72);c.fillStyle=tone(color,.8);c.strokeStyle=tone(color,1.35);c.lineWidth=1.1*r.dpr;if(glowColor){c.shadowColor=glowColor;c.shadowBlur=7*r.dpr}c.beginPath();c.arc(0,0,radius,0,Math.PI*2);c.fill();c.stroke();c.restore()}
export function line(r,a,m,x,y,color,w,k,alpha=.8){line2(r.ctx,project(r,a,x,m,k),project(r,a,y,m,k),color,w*r.dpr,alpha)}
export function line2(c,x,y,color,w,alpha=1){if(!Number.isFinite(x?.x)||!Number.isFinite(x?.y)||!Number.isFinite(y?.x)||!Number.isFinite(y?.y))return;c.save();c.globalAlpha=finite(alpha,1);c.strokeStyle=color;c.lineWidth=Math.max(0,finite(w));c.lineCap='round';c.beginPath();c.moveTo(x.x,x.y);c.lineTo(y.x,y.y);c.stroke();c.restore()}
export function glow(r,a,m,p,size,color,k,alpha=1){const q=project(r,a,p,m,k),px=Math.max(.001,finite(size)*Math.max(.001,finite(r.scale,1))*Math.max(.001,finite(k,1))),c=r.ctx;c.save();c.globalCompositeOperation='lighter';c.globalAlpha=finite(alpha,1);const g=c.createRadialGradient(q.x,q.y,0,q.x,q.y,px);g.addColorStop(0,'rgba(255,255,255,.96)');g.addColorStop(.28,tone(color,1.15,.9));g.addColorStop(1,tone(color,1,0));c.fillStyle=g;c.beginPath();c.arc(q.x,q.y,px,0,Math.PI*2);c.fill();c.restore()}
export function shadow(r,a,k){const p=r.worldToScreen(finite(a.x)-.08,finite(a.y)+.2),scale=Math.max(.001,finite(r.scale,1)),model=Math.max(.001,finite(k,1)),c=r.ctx;c.save();c.translate(finite(p?.x),finite(p?.y));c.scale(1,.42);c.fillStyle='rgba(0,0,0,.38)';c.beginPath();c.ellipse(0,0,scale*.82*model,scale*.4*model,0,0,Math.PI*2);c.fill();c.restore()}
